# Generated by Django 4.2.7 on 2023-11-26 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvgGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField(default=datetime.datetime(2023, 11, 26, 3, 15, 7, 547238))),
                ('is_base', models.BooleanField(default=False)),
            ],
        ),
    ]
