# Generated by Django 4.2.7 on 2023-11-27 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avg_graphs', '0002_alter_avggraph_date_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avggraph',
            name='date_finish',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 21, 15, 26, 963909)),
        ),
    ]
