# Generated by Django 4.2.7 on 2023-11-27 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avg_graphs', '0003_alter_avggraph_date_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avggraph',
            name='date_finish',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 21, 55, 47, 871244)),
        ),
        migrations.AlterField(
            model_name='avggraph',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 21, 55, 47, 871244)),
        ),
    ]
