# Generated by Django 4.2.7 on 2023-11-26 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avg_graphs', '0002_alter_avggraph_date_finish'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgGraphInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=50)),
                ('total_count', models.IntegerField()),
                ('avg', models.IntegerField()),
                ('avg_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avg_graph', to='avg_graphs.avggraph')),
            ],
        ),
    ]
