# Generated by Django 4.2.7 on 2023-11-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avg_graph_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avggraphinfo',
            name='avg',
            field=models.FloatField(),
        ),
    ]
